apiVersion: skaffold/v2beta10
kind: Config
deploy:
  helm:
    releases:
    - name: frontend
      namespace: example
      createNamespace: true
      chartPath: tmp/rendered/frontend
    - name: backend
      namespace: example
      createNamespace: true
      chartPath: tmp/rendered/backend