values:
  scalar: 1
  tree:
    scalar: tree-scalar
  array:
    - node1
    - node2
  map:
    - node1: val1
      prop11: pv11
    - node2: val2
      prop21: pv21
  frontend:
    prod: frontend-prod-value
  backend:
    prod: backend-prod-value
charts:
  - name: rendered-frontend
    path: ./examples/charts/frontend
    additionlValues:
      - values.prod.yaml
    appVersion: 1.0.1
  - name: rendered-backend
    path: ./examples/charts/backend
    additionlValues:
      - values.prod.yaml
    appVersion: 1.0.2
outputFolder: ./tmp/rendered