apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app.kubernetes.io/component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/component: frontend
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
        - name: main
          image: alpine:3.13.2
          command:
            - /bin/sh
            - '-c'
            - 'while printf "chart appVersion: {{ .Chart.AppVersion }}\nscalar: $SCALAR\ntree scalar: $TREE_SCALAR\narray: $ARRAY\nmap: $MAP\noverride: $OVERRIDE\n---\n"; sleep 1; do :; done'
          env:
            - name: SCALAR
              value: {{ .Values.scalar }}
            - name: TREE_SCALAR
              value: {{ .Values.tree.scalar }}
            - name: ARRAY
              value: "{{ .Values.array }}"
            - name: MAP
              value: "{{ .Values.map }}"
            - name: OVERRIDE
              value: {{ .Values.override }}